### ISSUE TITLE
Enable Fedora 32 builds in Copr

### ISSUE THREAD

**Issue by dawud** [e-minguez/rpms#30]
Since Fedora is now GA, builds for Fedora 32 can be enabled.

Thanks!

**Comment by e-minguez** [comment]
> Since Fedora is now GA, builds for Fedora 32 can be enabled.
> 
> Thanks!

Done. Builds have been queued with F32 enabled https://copr.fedorainfracloud.org/coprs/eminguez/eminguez-RPMs/builds/

Thanks!

**Comment by e-minguez** [comment]
It seems they have been built! https://download.copr.fedorainfracloud.org/results/eminguez/eminguez-RPMs/fedora-32-x86_64/01422852-terraform/terraform-0.12.18-1.fc32.x86_64.rpm
