### ISSUE TITLE
Add packer-bash-completion

### ISSUE THREAD

**Issue by e-minguez** [e-minguez/rpms#4]
https://github.com/mrolli/packer-bash-completion

**Comment by dawud** [comment]
There seems to be a [built-in capability now for this](https://www.packer.io/docs/commands/index.html#autocompletion), but I can't get it to work, maybe because [it's a mock-up at this moment](https://github.com/hashicorp/packer/blob/master/vendor/github.com/mitchellh/cli/autocomplete.go)
